version: '2'
networks:
  mining:
    name: mining
    driver: bridge
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.retention.size=1GB
    volumes:
    - ./prometheus:/etc/prometheus:ro
    depends_on:
    - exporter
    networks:
      - mining
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
    - grafana_etc:/etc/grafana
    - grafana_var_lib:/var/lib/grafana
    - ./provisioning:/etc/grafana/provisioning
    depends_on:
    - prometheus
    networks:
     - mining
    restart: always

  exporter:
    container_name: exporter
    build: mining-exporter
    volumes:
    - exporter_data:/prometheus-mining
    network_mode: host
    environment:
    - RIGS=${RIGS}
    restart: always

networks:
  - mining
  front:
    driver: bridge

volumes:
  grafana_var_lib:
  grafana_etc:
  exporter_data:
  
